#!/bin/bash

LOG_FILE="/roms/logs/retroarch32_tate.log"
echo "Loading Emulator: Retroarch32 TATE" | tee $LOG_FILE
echo "Loading Emulator Path: $0" | tee -a $LOG_FILE
echo "Loading Core Path: $2" | tee -a $LOG_FILE
echo -e "Loading ROM Path: $3\n" | tee -a $LOG_FILE

echo "Entering TATE Mode" | tee -a $LOG_FILE

tate_config_files()
{
   local TATE_CORE_FILE=$1
   local FILE=$2
   local TATE_FILE=$3
   local NORMAL_FILE=$4

   if [ ! -f "$TATE_FILE" ] && [ -f "$TATE_CORE_FILE" ]; then
      echo "TATE_FILE '$TATE_FILE': NOT exist" | tee -a $LOG_FILE
      echo "Copying TATE_CORE_FILE '$TATE_CORE_FILE' to TATE_FILE '$TATE_FILE'" | tee -a $LOG_FILE
      sudo cp "$TATE_CORE_FILE" "$TATE_FILE"
      sudo chmod 666 "$TATE_FILE"
      sudo chown ark:ark "$TATE_FILE"
   fi

   if [ -f "$TATE_FILE" ]; then
      echo "TATE_FILE '$TATE_FILE': exist" | tee -a $LOG_FILE
      if [ -f "$FILE" ]; then
         echo "FILE '$FILE': exist" | tee -a $LOG_FILE
         if [ -f "$NORMAL_FILE" ]; then
           echo "NORMAL_FILE '$NORMAL_FILE': exist, removing" | tee -a $LOG_FILE
           sudo rm -f "$NORMAL_FILE"
         fi
         echo "Moving FILE '$FILE' to NORMAL_FILE '$NORMAL_FILE'" | tee -a $LOG_FILE
         sudo mv "$FILE" "$NORMAL_FILE"
      fi
      echo "Moving TATE_FILE '$TATE_FILE' to FILE '$FILE'" | tee -a $LOG_FILE
      sudo mv "$TATE_FILE" "$FILE"

      # fix deafult control index
      local previous_player=$(head -n1 "$FILE")
      previous_player="${previous_player//# player: /}"
      echo "Default controller, previous player: '$previous_player'" | tee -a $LOG_FILE
      if [ -z "$previous_player" ] || [[ $previous_player == *"input_"* ]]; then
         previous_player="1"
         echo "Setting default controller previous player to '$previous_player'" | tee -a $LOG_FILE;
      fi

      local player=$(/usr/local/bin/es-controllers get default_controller_player)
      echo "Default controller, new player: '$player'" | tee -a $LOG_FILE
      [ -z "$player" ] && player=1; echo "Setting default controller player to '$player'" | tee -a $LOG_FILE;
      sed -i 's/input_libretro_device_p'"$previous_player"' =/input_libretro_device_p'"$player"' =/g; s/_player'"$previous_player"'_/_player'"$player"'_/g' "$FILE"
   fi
}

tate_restore_files()
{
   local FILE=$1
   local TATE_FILE=$2
   local NORMAL_FILE=$3

   if [ -f "$FILE" ]; then
      echo "FILE '$FILE' exist" | tee -a $LOG_FILE
      if [ -f "$TATE_FILE" ]; then
         echo "TATE_FILE '$TATE_FILE' exist, removing" | tee -a $LOG_FILE
         sudo rm -f "$TATE_FILE"
      fi
      echo "Moving FILE '$FILE' to TATE_FILE '$TATE_FILE'" | tee -a $LOG_FILE
      sudo mv "$FILE" "$TATE_FILE"
      local player=$(/usr/local/bin/es-controllers get default_controller_player)
      sed  -i '1i # player: '"$player"'' "$TATE_FILE"
   fi
   if [ -f "$NORMAL_FILE" ]; then
      echo "NORMAL_FILE '$NORMAL_FILE' exist" | tee -a $LOG_FILE
      if [ -f "$FILE" ]; then
         echo "FILE '$FILE' exist, removing" | tee -a $LOG_FILE
         sudo rm -f "$FILE"
      fi
      echo "Moving NORMAL_FILE '$NORMAL_FILE' to FILE '$FILE'" | tee -a $LOG_FILE
      sudo mv "$NORMAL_FILE" "$FILE"
   fi
}


CORE_FILE=$(basename "$2")
CORE="${CORE_FILE%_libretro.so}"
CORE_NAME=""
GAME="$3"
EXTRA_PARAMETERS=""
VERT_MODE="disabled"

RETROARCH_CONFIG_DIR="/home/ark/.config/retroarch32"
RA_CONTROLLER_CONFIG_FILE="${RETROARCH_CONFIG_DIR}/retroarch.cfg.ext"
echo "RETROARCH_CONFIG_DIR: '$RETROARCH_CONFIG_DIR'" | tee -a $LOG_FILE
echo "RA_CONTROLLER_CONFIG_FILE: '$RA_CONTROLLER_CONFIG_FILE'" | tee -a $LOG_FILE

RA_CORE_OPTIONS_FILE="$RETROARCH_CONFIG_DIR/retroarch-core-options.cfg"
OPTIONS_FILE="$RA_CORE_OPTIONS_FILE"

if [[ $CORE == "mame2003_xtreme" ]]; then
  CORE_NAME="MAME 2003"
fi


CORE_OPTIONS_FILE="$RETROARCH_CONFIG_DIR/config/$CORE_NAME/$CORE_NAME.opt"
GAME_NAME=$(basename "$GAME")
GAME_NAME="${GAME_NAME%.*}"
GAME_OPTIONS_FILE="$RETROARCH_CONFIG_DIR/config/$CORE_NAME/$GAME_NAME.opt"
TATE_CORE_REMAP_FILE="$RETROARCH_CONFIG_DIR/remaps-tate/$CORE_NAME/$CORE_NAME.rmp.tate"
GAME_REMAP_FILE="$RETROARCH_CONFIG_DIR/config/remaps/$CORE_NAME/$GAME_NAME.rmp"
TATE_GAME_REMAP_FILE="$RETROARCH_CONFIG_DIR/config/remaps/$CORE_NAME/$GAME_NAME.rmp.tate"
NORMAL_GAME_REMAP_FILE="$RETROARCH_CONFIG_DIR/config/remaps/$CORE_NAME/$GAME_NAME.rmp.normal"

DEFAULT_CONTROLLER="$RETROARCH_CONFIG_DIR/autoconfig/udev/retrogame_joypad.cfg"

echo "RA_CORE_OPTIONS_FILE: '$RA_CORE_OPTIONS_FILE'" | tee -a $LOG_FILE
echo "CORE_FILE: '$CORE_FILE'" | tee -a $LOG_FILE
echo "CORE_NAME: '$CORE_NAME'" | tee -a $LOG_FILE
echo "CORE: '$CORE'" | tee -a $LOG_FILE
echo "CORE_OPTIONS_FILE: '$CORE_OPTIONS_FILE'" | tee -a $LOG_FILE
echo "GAME_NAME: '$GAME_NAME'" | tee -a $LOG_FILE
echo "GAME_OPTIONS_FILE: '$GAME_OPTIONS_FILE'" | tee -a $LOG_FILE
echo "TATE_CORE_REMAP_FILE: '$TATE_CORE_REMAP_FILE'" | tee -a $LOG_FILE
echo "GAME_REMAP_FILE: '$GAME_REMAP_FILE'" | tee -a $LOG_FILE
echo "TATE_GAME_REMAP_FILE: '$TATE_GAME_REMAP_FILE'" | tee -a $LOG_FILE
echo "NORMAL_GAME_REMAP_FILE: '$NORMAL_GAME_REMAP_FILE'" | tee -a $LOG_FILE


if [ -f "$GAME_OPTIONS_FILE" ]; then
   OPTIONS_FILE="$GAME_OPTIONS_FILE"
elif [ -f "$CORE_OPTIONS_FILE" ]; then
   OPTIONS_FILE="$CORE_OPTIONS_FILE"
fi
echo "OPTIONS_FILE: $OPTIONS_FILE" | tee -a $LOG_FILE

if [[ $CORE == "mame2003_xtreme" ]]; then
   VERT_MODE=$(cat "$OPTIONS_FILE" | grep "mame2003-option_tate_mode" | grep -oP '"\K[^"]+')
   if [ -z "$VERT_MODE" ]; then
      sudo sed -i -e '$amame2003-option_tate_mode \= "enabled"' "$OPTIONS_FILE"
   else
      sudo sed -i '/mame2003-option_tate_mode \=/c\mame2003-option_tate_mode \= "enabled"' "$OPTIONS_FILE"
   fi
fi

if [ -z "$VERT_MODE" ]; then
   VERT_MODE="disabled"
fi
echo "Getting actual VERT_MODE: '${VERT_MODE}'" | tee -a $LOG_FILE

# Test previous fail to restore rempas files
if [[ $VERT_MODE == "alternate" ]] || [[ $VERT_MODE == "enabled" ]]; then
   # restore core configuration
   echo "Restoring previous fail configuration" | tee -a $LOG_FILE
   tate_restore_files "$GAME_REMAP_FILE" "$TATE_GAME_REMAP_FILE" "$NORMAL_GAME_REMAP_FILE"
   VERT_MODE="disabled"
   echo "Changed VERT_MODE to '${VERT_MODE}'" | tee -a $LOG_FILE
fi

   tate_config_files "$TATE_CORE_REMAP_FILE" "$GAME_REMAP_FILE" "$TATE_GAME_REMAP_FILE" "$NORMAL_GAME_REMAP_FILE"

# configure controllers
echo "Configuring controls" | tee -a $LOG_FILE
/usr/local/bin/es-controllers config_controllers RETROARCH32 "true"

EXTRA_CONFIGURATIONS=""
if [ -f "${RETROARCH_CONFIG_DIR}/retroarch.cfg.ext" ]; then
    EXTRA_CONFIGURATIONS="--appendconfig=${RETROARCH_CONFIG_DIR}/retroarch.cfg.ext"
fi
echo "EXTRA_CONFIGURATIONS: $EXTRA_CONFIGURATIONS" | tee -a $LOG_FILE

# launching emulator
echo "COMMAND: /opt/retroarch/bin/retroarch32 -c $RETROARCH_CONFIG_DIR/retroarch.cfg $EXTRA_CONFIGURATIONS -L $RETROARCH_CONFIG_DIR/cores/${CORE}_libretro.so \"$GAME\"" | tee -a $LOG_FILE

/usr/local/bin/es-splash_screen quit_splash_before_game
/opt/retroarch/bin/retroarch32 -c "$RETROARCH_CONFIG_DIR"/retroarch.cfg $EXTRA_CONFIGURATIONS -L "$RETROARCH_CONFIG_DIR"/cores/"$CORE"_libretro.so "$GAME"
/usr/local/bin/es-splash_screen load_splash_after_game


echo "Exiting TATE Mode" | tee -a $LOG_FILE

tate_restore_files "$GAME_REMAP_FILE" "$TATE_GAME_REMAP_FILE" "$NORMAL_GAME_REMAP_FILE"

# restore core configuration
echo "Restoring VERT_MODE: '${VERT_MODE}' on '$OPTIONS_FILE'" | tee -a $LOG_FILE
if [[ $CORE == "mame2003_xtreme" ]]; then
   sudo sed -i "/mame2003-option_tate_mode \=/c\mame2003-option_tate_mode \= \"${VERT_MODE}\"" "$OPTIONS_FILE"
fi

# reset controllers configuration
echo "removing retroarch configuration file" | tee -a $LOG_FILE
/usr/local/bin/es-controllers remove_controllers_config RETROARCH32 &

echo -e "Exiting...\n" | tee -a $LOG_FILE
