#!/usr/bin/env bash

LOG_FILE="/roms/logs/retroarch.log"
echo "Loading Emulator: Retroarch" | tee $LOG_FILE
echo "Loading Emulator Path: $0" | tee -a $LOG_FILE
echo "Loading Core Path: $2" | tee -a $LOG_FILE
echo -e "Loading ROM Path: $3\n" | tee -a $LOG_FILE


CORE_FILE=$(basename "$2")
CORE="${CORE_FILE%_libretro.so}"
GAME="$3"
RETROARCH_CONFIG_DIR="/home/ark/.config/retroarch"

echo "CORE_FILE: '$CORE_FILE'" | tee -a $LOG_FILE
echo "CORE: '$CORE'" | tee -a $LOG_FILE
echo "GAME: '$GAME'" | tee -a $LOG_FILE
echo "RETROARCH_CONFIG_DIR: '$RETROARCH_CONFIG_DIR'" | tee -a $LOG_FILE

# configure controllers
echo "Configuring controls" | tee -a $LOG_FILE
/usr/local/bin/es-controllers config_controllers RETROARCH

EXTRA_CONFIGURATIONS=""
if [ -f "${RETROARCH_CONFIG_DIR}/retroarch.cfg.ext" ]; then
    EXTRA_CONFIGURATIONS="--appendconfig=${RETROARCH_CONFIG_DIR}/retroarch.cfg.ext"
fi
echo "EXTRA_CONFIGURATIONS: $EXTRA_CONFIGURATIONS" | tee -a $LOG_FILE

# launching emulator
echo "COMMAND: /opt/retroarch/bin/retroarch -c $RETROARCH_CONFIG_DIR/retroarch.cfg $EXTRA_CONFIGURATIONS -L $RETROARCH_CONFIG_DIR/cores/${CORE}_libretro.so \"$GAME\"" | tee -a $LOG_FILE

/usr/local/bin/es-splash_screen quit_splash_before_game
/opt/retroarch/bin/retroarch -c "$RETROARCH_CONFIG_DIR"/retroarch.cfg $EXTRA_CONFIGURATIONS -L "$RETROARCH_CONFIG_DIR"/cores/"$CORE"_libretro.so "$GAME"
/usr/local/bin/es-splash_screen load_splash_after_game


echo "removing retroarch configuration file" | tee -a $LOG_FILE
/usr/local/bin/es-controllers remove_controllers_config RETROARCH &

echo -e "Exiting...\n" | tee -a $LOG_FILE
