#!/bin/sh

export USER_HOME_PATH="/home/odroid"
export ES_HOME_PATH="$USER_HOME_PATH/.emulationstation"
export ES_CONFIG_FILE="$ES_HOME_PATH/es_settings.cfg"
export ES_BRIGTHNESS_LOCK_FILE="$ES_HOME_PATH/brightness.lock"
export ES_PRELOAD_VLC_LOCK_FILE="$ES_HOME_PATH/preload_vlc.lock"
export RA_CONFIG_FOLDER="$USER_HOME_PATH/.config/retroarch"
export RA32_CONFIG_FOLDER="$USER_HOME_PATH/.config/retroarch32"
export ES_SCRIPTS_PATH="/usr/local/bin"
export ROMS_DIR="/roms"

#******************* ES Scripts String functions ********************
trim()
{
  local trimmed="$1"

  # Strip leading spaces.
  while [[ $trimmed == ' '* ]]; do
     trimmed="${trimmed## }"
  done
  # Strip trailing spaces.
  while [[ $trimmed == *' ' ]]; do
      trimmed="${trimmed%% }"
  done

  echo "$trimmed"
}
#******************* END - ES Scripts String functions ********************
