#!/bin/bash

do_help()
{
	echo "Usage:" >&2
	echo "" >&2
	echo "$0 set [key] [value] <CONTROLLER_CONFIG_FILE>" >&2
	echo "Valid keys: ra_turbo_button" >&2
	echo "" >&2
	echo "or" >&2
	echo "" >&2
	echo "$0 get <CONTROLLER_CONFIG_FILE>" >&2
	echo "Valid keys: ra_turbo_button" >&2
	echo "" >&2
	echo "or" >&2
	echo "" >&2
	echo "$0 get [key]" >&2
	echo "Valid keys: turbo_button, turbo_button_tate, default_controller_index, controllers_number" >&2
	echo "" >&2
	echo "or" >&2
	echo "" >&2
	echo "$0 config__controllers <EMULATOR> <CONFIG_FILE>" >&2
	echo "Valid emulators: RETROARCH" >&2
	echo "" >&2
}

get_ra_button_property()
{
    local es_button="$1"

    case "${es_button}" in
        "Up")
            echo "input_up_btn"
        ;;
        "Down")
            echo "input_down_btn"
        ;;
        "Left")
            echo "input_left_btn"
        ;;
        "Right")
            echo "input_right_btn"
        ;;
        "Select")
            echo "input_select_btn"
        ;;
        "Start")
            echo "input_start_btn"
        ;;
        "A")
            echo "input_a_btn"
        ;;
        "B")
            echo "input_b_btn"
        ;;
        "X")
            echo "input_x_btn"
        ;;
        "Y")
            echo "input_y_btn"
        ;;
        "LeftShoulder")
            echo "input_l_btn"
        ;;
        "RightShoulder")
            echo "input_r_btn"
        ;;
        "LeftTrigger")
            echo "input_l2_btn"
        ;;
        "RightTrigger")
            echo "input_r2_btn"
        ;;
        "LeftThumb")
            echo "input_l3_btn"
        ;;
        "RightThumb")
            echo "input_r3_btn"
        ;;
        "LeftAnalogUp")
            echo "input_l_y_minus_axis"
        ;;
        "LeftAnalogDown")
            echo "input_l_y_plus_axis"
        ;;
        "LeftAnalogLeft")
            echo "input_l_x_minus_axis"
        ;;
        "LeftAnalogRight")
            echo "input_l_x_plus_axis"
        ;;
        "RightAnalogUp")
            echo "input_r_y_minus_axis"
        ;;
        "RightAnalogDown")
            echo "input_r_y_plus_axis"
        ;;
        "RightAnalogLeft")
            echo "input_r_x_minus_axis"
        ;;
        "RightAnalogRight")
            echo "input_r_x_plus_axis"
        ;;
        *)
            echo ""
    esac
}

do_set_ra_turbo_button()
{
    local ra_turbo_button=$1
    local controller_file=$2

    #print_log $LOG_FILE "INFO" "Executing 'do_set_ra_turbo_button()' - RA button '$ra_turbo_button', controller configuration file '$controller_file'"
    if [ -z "$ra_turbo_button" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_set_ra_turbo_button()' - RA button is empty, skipping..."
        return
    fi
    if [ -z "$controller_file" ] || [ ! -f "$controller_file" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_set_ra_turbo_button()' - controller configuration file parameter is empty or file doesn't exist: '$controller_file'"
        return
    fi
    local turbo_button_value=$(get_ra_property "$controller_file" "$ra_turbo_button")
    if [ -z "$turbo_button_value" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_set_ra_turbo_button()' - RA button property '$ra_turbo_button' value on file '$controller_file' is empty, skipping..."
        return
    fi
    #print_log $LOG_FILE "DEBUG" "Executing 'do_set_ra_turbo_button()' - updating file '$controller_file', turbo button '$ra_turbo_button' and value '$turbo_button_value'"
    set_ra_property "$controller_file" "$DEFAULT_RA_TURBO_BUTTON_PROPERTY" "$turbo_button_value"
}

do_set_ra_turbo_button_value()
{
    local turbo_button_value=$1
    local controller_file=$2

    #print_log $LOG_FILE "INFO" "Executing 'do_set_ra_turbo_button_value()' - RA turbo button value '$ra_turbo_button_value', controller configuration file '$controller_file'"

    if [ -z "$turbo_button_value" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_set_ra_turbo_button_value()' -  RA turbo button value is empty, skipping..."
        return
    fi
    if  [ -z "$controller_file" ] || [ ! -f "$controller_file" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_set_ra_turbo_button_value()' - controller configuration file parameter is empty or file doesn't exist: '$controller_file'"
        echo ""
        return
    fi
    #print_log $LOG_FILE "DEBUG" "Executing 'do_set_ra_turbo_button_value()' - updating file '$controller_file', turbo button value '$turbo_button_value'"
    set_ra_property "$controller_file" "$DEFAULT_RA_TURBO_BUTTON_PROPERTY" "$turbo_button_value"
}

do_config_set_value()
{
    local key=$1
    local value=$2
    local controller_config_file=$3

    #print_log $LOG_FILE "INFO" "Executing 'do_config_set_value()' - key: '$key', value: '$value', controller_config_file: '$parameter'"

    case "${key}" in
        "ra_turbo_button")
            # parameter is a controller configuration file
            do_set_ra_turbo_button "$value" "$controller_config_file"
        ;;
        "ra_turbo_button_value")
            # parameter is a controller configuration file
            do_set_ra_turbo_button_value "$value" "$controller_config_file"
        ;;
        *)
            do_help
            >&2 echo "error: invalid set command ${key}"
            #print_log $LOG_FILE "ERROR" "Executing 'do_config_set_value()' - ##### Invalid get command ${key} #####"
            exit 1
    esac
}

do_get_turbo_button()
{
    local turbo_button=$(get_es_settings_property "TurboHotkeyButton")
    [ -z "$turbo_button" ] && turbo_button="LeftThumb"

    #print_log $LOG_FILE "INFO" "Executing 'do_get_turbo_button()' - ES button '$turbo_button'"
    echo "$turbo_button"
}

do_get_turbo_button_tate()
{
    local turbo_button=$(get_es_settings_property "TurboHotkeyButtonTate")
    [ -z "$turbo_button" ] && turbo_button="RightThumb"

    #print_log $LOG_FILE "INFO" "Executing 'do_get_turbo_button_tate()' - ES button '$turbo_button'"
    echo "$turbo_button"
}

do_get_ra_turbo_button()
{
    local es_turbo_button="$(do_get_turbo_button)"
    local ra_button_property=$(get_ra_button_property $es_turbo_button)

    #print_log $LOG_FILE "INFO" "Executing 'do_get_turbo_button()' - ES button '$es_turbo_button', Ra turbo button '$ra_button_property'"
    echo "$ra_button_property"
}

do_get_ra_turbo_button_tate()
{
    local es_turbo_button="$(do_get_turbo_button_tate)"
    local ra_button_property=$(get_ra_button_property $es_turbo_button)

    #print_log $LOG_FILE "INFO" "Executing 'do_get_ra_turbo_button_tate()' - ES button '$es_turbo_button', Ra turbo button '$ra_button_property'"
    echo "$ra_button_property"
}

do_get_ra_turbo_button_value()
{
    local controller_file=$1
    local es_turbo_button=$(do_get_turbo_button)

    local ra_button_property=$(get_ra_button_property $es_turbo_button)
    if [ -z "$ra_button_property" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_get_ra_turbo_button_value()' - ES turbo button '$es_turbo_button', RA button property is empty, skipping..."
        echo ""
        return
    fi
    #print_log $LOG_FILE "INFO" "Executing 'do_get_ra_turbo_button_value()' - ES button '$es_turbo_button', controller configuration file '$controller_file'"
    if  [ -z "$controller_file" ] || [ ! -f "$controller_file" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_get_ra_turbo_button_value()' - controller configuration file parameter is empty or file doesn't exist: '$controller_file'"
        echo ""
        return
    fi
    local ra_turbo_button_value=$(get_ra_property "$controller_file" "$ra_button_property")
    #print_log $LOG_FILE "INFO" "Executing 'do_get_ra_turbo_button_value()' - controller configuration file '$controller_file', RA button '$ra_button_property', value '$ra_turbo_button_value'"
    echo "$ra_turbo_button_value"
}

do_get_ra_turbo_button_tate_value()
{
    local controller_file=$1
    local es_turbo_button=$(do_get_turbo_button_tate)

    local ra_button_property=$(get_ra_button_property $es_turbo_button)
    if [ -z "$ra_button_property" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_get_ra_turbo_button_tate_value()' - ES turbo button '$es_turbo_button', RA button property is empty, skipping..."
        echo ""
        return
    fi
    #print_log $LOG_FILE "INFO" "Executing 'do_get_ra_turbo_button_tate_value()' - ES button '$es_turbo_button', controller configuration file '$controller_file'"
    if  [ -z "$controller_file" ] || [ ! -f "$controller_file" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_get_ra_turbo_button_tate_value()' - controller configuration file parameter is empty or file doesn't exist: '$controller_file'"
        echo ""
        return
    fi
    local ra_turbo_button_value=$(get_ra_property "$controller_file" "$ra_button_property")
    #print_log $LOG_FILE "INFO" "Executing 'do_get_ra_turbo_button_tate_value()' - controller configuration file '$controller_file', RA button '$ra_button_property', value '$ra_turbo_button_value'"
    echo "$ra_turbo_button_value"
}

do_get_default_controller_index()
{
    #print_log $LOG_FILE "INFO" "Executing 'do_get_default_controller_index()'"
    local index="0"

    if [ -f "$INPUT_CONTROLLERS_CONFIG_PATH" ]; then
        local controller_info=$(tac "$INPUT_CONTROLLERS_CONFIG_PATH" | grep "retrogame_joypad" -m 1 -B 9999 | tac)
        index=$(echo "$controller_info" | grep "index" | head -n1 | tr -s ' ' | cut -d ' ' -f 4 | cut -d ',' -f 1)
        [ -z "$index" ] && index="0"
    fi
    #print_log $LOG_FILE "INFO" "Executing 'do_get_default_controller_index()' - at index '$index'"
    echo "$index"
}

do_get_default_controller_player()
{
    #print_log $LOG_FILE "INFO" "Executing 'do_get_default_controller_player()'"
    local player="1"

    if [ -f "$INPUT_CONTROLLERS_CONFIG_PATH" ]; then
        local controller_info=$(tac "$INPUT_CONTROLLERS_CONFIG_PATH" | grep "retrogame_joypad" -m 1 -B 9999 | tac)
        player=$(echo "$controller_info" | grep "player" | head -n1 | tr -s ' ' | cut -d ' ' -f 4 | cut -d ',' -f 1)
        [ -z "$player" ] && player="1"
    fi
    #print_log $LOG_FILE "INFO" "Executing 'do_get_default_controller_player()' - at player '$player'"
    echo "$player"
}

do_get_controllers_number()
{
    local num_controllers=$(cat "$INPUT_CONTROLLERS_CONFIG_PATH" | grep "player" | wc -l)
    #print_log $LOG_FILE "INFO" "Executing 'do_get_controllers_number()' - number of controllers: '$num_controllers'"

    echo "$num_controllers"
}

do_config_get_value()
{
    local key=$1
    local controller_config_file=$2

    #print_log $LOG_FILE "INFO" "Executing 'do_config_get_value()' - key: '$key', parameter: '$parameter'"

    case "${key}" in
        "turbo_button")
            do_get_turbo_button
        ;;
        "turbo_button_tate")
            do_get_turbo_button_tate
        ;;
        "ra_turbo_button")
            do_get_ra_turbo_button
        ;;
        "ra_turbo_button_value")
            # parameter is a controller configuration file
            do_get_ra_turbo_button_value "$controller_config_file"
        ;;
        "ra_turbo_button_tate")
            # parameter is a controller configuration file
            do_get_ra_turbo_button_tate
        ;;
        "ra_turbo_button_tate_value")
            # parameter is a controller configuration file
            do_get_ra_turbo_button_tate_value "$controller_config_file"
        ;;
        "default_controller_index")
            do_get_default_controller_index
        ;;
        "default_controller_player")
            do_get_default_controller_player
        ;;
        "controllers_number")
            do_get_controllers_number
        ;;
        *)
            do_help
            >&2 echo "error: invalid get command ${key}"
            #print_log $LOG_FILE "Executing 'do_config_get_value()' - ERROR" "##### Invalid get command ${key} #####"
            exit 1
    esac
}

do_remove_ra_turbo_button()
{
    local controller_file=$1
    #print_log $LOG_FILE "INFO" "Executing 'do_remove_ra_turbo_button()' - RA button to remove: '$DEFAULT_RA_TURBO_BUTTON_PROPERTY' on controller config file '$controller_file'"

    if  [ -z "$controller_file" ] || [ ! -f "$controller_file" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_remove_ra_turbo_button()' - controller configuration file parameter is empty or file doesn't exist, skipping..."
        return
    fi

    remove_ra_property "$controller_file" "$DEFAULT_RA_TURBO_BUTTON_PROPERTY"
}

do_config_remove_value()
{
    local key=$1
    local parameter=$2

    #print_log $LOG_FILE "INFO" "Executing 'do_config_remove_value()' - key: '$key', parameter: '$parameter'"

    case "${key}" in
        "ra_turbo_button")
            # parameter is a controller configuration file
            do_remove_ra_turbo_button "$parameter"
        ;;
        *)
            do_help
            >&2 echo "error: invalid remove command ${key}"
            #print_log $LOG_FILE "Executing 'do_config_remove_value()' - ERROR" "##### Invalid get command ${key} #####"
            exit 1
    esac
}

do_get_controller_hotkey_button_data()
{
    local controller_name="$1"

    #print_log $LOG_FILE "INFO" "Executing 'do_get_controller_hotkey_button()' - searching hotkey of controller '$controller_name', on ES input controller file '$ES_INPUT_CFG_FILE'"

    local controller_def=$(tac ${ES_INPUT_CFG_FILE} | grep "${controller_name}" -m 1 -B 9999 | tac)
    local hotkey_def=$(echo "${controller_def}" | grep "name=\"hotkey" | head -n1)
    #print_log $LOG_FILE "INFO" "Executing 'do_get_controller_hotkey_button()' - hotkey definition '$hotkey_def'"

    # test if it is button
    if [[ $hotkey_def != *"button"* ]]; then
       #print_log $LOG_FILE "INFO" "Executing 'do_get_controller_hotkey_button()' - hotkey is not a button, skipping..."
       echo ""
       return
    fi
    local hotkey_value=$(echo "$hotkey_def" | grep -o -P -w 'id="\K[^"]+')
    local hotkey_name=$(echo "${controller_def}" | grep button | grep "id=\"0\"" | head -n1)

    #print_log $LOG_FILE "INFO" "Executing 'do_get_controller_hotkey_button()' - hotkey data [name='$hotkey_name', value='$hotkey_value']"
    echo "$hotkey_name;$hotkey_value"
}

do_config_hotkeys_retroarch()
{
    local config_file="$1"
    local ra_controller_input_cfg="$2"

    #print_log $LOG_FILE "INFO" "Executing 'do_config_hotkeys_retroarch()' - on player one, RA config file '$config_file', RA controller config file '$ra_controller_input_cfg'"

    # setting hotkey, default SELECT button
    local hotkey_data=$(do_get_controller_hotkey_button_data)
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey data '$hotkey_data'"
    local ra_button_value=""

    if [ ! -z "$hotkey_data" ]; then
       local hotkey_name=$(echo "$hotkey_data" | sed 's/;.*//g')
       ra_button_value=$(echo "$hotkey_data" | sed 's/.*;//g')
       #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_enable_hotkey_btn', default button '${hotkey_name^^}', device button value '$ra_button_value'"
    else
       ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_select_btn" "")
       #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_enable_hotkey_btn', default button 'SELECT', device button value '$ra_button_value'"
    fi

    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_enable_hotkey_btn" "$ra_button_value"

    # setting exit emulator to START button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_start_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_exit_emulator_btn', default button 'START', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_exit_emulator_btn" "$ra_button_value"

    # setting IA service to A button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_a_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_ai_service_btn', default button 'A', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_ai_service_btn" "$ra_button_value"

    # setting save state service to R button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_r_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_save_state_btn', default button 'R1', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_save_state_btn" "$ra_button_value"

    # setting load state service to L button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_l_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_load_state_btn', default button 'L1', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_load_state_btn" "$ra_button_value"

    # setting menu toggle service to X button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_x_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_menu_toggle_btn', default button 'X', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_menu_toggle_btn" "$ra_button_value"

    # setting reset game to R3 button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_r3_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_reset_btn', default button 'R3', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_reset_btn" "$ra_button_value"

    # setting rewind to Y button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_y_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_rewind_btn', default button 'Y', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_rewind_btn" "$ra_button_value"

    # setting state slot decrease to L2 button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_l2_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_state_slot_decrease_btn', default button 'L2', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_state_slot_decrease_btn" "$ra_button_value"

    # setting state slot increase to R2 button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_r2_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_state_slot_increase_btn', default button 'R2', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_state_slot_increase_btn" "$ra_button_value"

    # setting toggle fast forward increase to B button
    ra_button_value=$(get_ra_property "$ra_controller_input_cfg" "input_b_btn" "")
    #print_log $LOG_FILE "DEBUG" "Executing 'do_config_hotkeys_retroarch()' - hotkey 'input_toggle_fast_forward_btn', default button 'B', device button value '$ra_button_value'"
    [ ! -z "$ra_button_value" ] && set_ra_property "$config_file" "input_toggle_fast_forward_btn" "$ra_button_value"
}

do_config_controllers_retroarch()
{
    local config_file=$1
    local autoconfig_folder=$2
    local tate_mode=$3

    #print_log $LOG_FILE "INFO" "Executing 'do_config_controllers_retroarch()' - configuration file: '$config_file', TATE mode '$tate_mode'"

    local num_controllers=$(do_get_controllers_number)

    #print_log $LOG_FILE "INFO" "Executing 'do_config_controllers_retroarch()' - configuration file: '$config_file', number of controllers: '$num_controllers'"

    for player in `seq 1 $MAX_PLAYERS`
    do
       local position=$((player - 1))
       local index=$(cat "$INPUT_CONTROLLERS_CONFIG_PATH" | jq '.['"$position"'].index')

       #print_log $LOG_FILE "INFO" "Executing 'do_config_controllers_retroarch()' - setting controller of player '$player' to index '$index'"
       if [ "$index" == "null" ]; then
          #print_log $LOG_FILE "INFO" "Executing 'do_config_controllers_retroarch()' - resetting controller '$position' to index 'nul'"
          set_ra_property "$config_file" "input_player${player}_joypad_index" "nul"
          continue
       fi

       set_ra_property "$config_file" "input_player${player}_joypad_index" $index

       # config turbo button
       local controller_name=$(jq '.['"$position"'].name' "$INPUT_CONTROLLERS_CONFIG_PATH")
       #print_log $LOG_FILE "INFO" "Executing 'do_config_controllers_retroarch()' - controller '$player', index '$index', name '$controller_name'"
       [ "$controller_name" == "null" ] && continue
       controller_name="${controller_name//\"/}"

       local ra_controller_input_cfg="$autoconfig_folder/${controller_name}.cfg"
       local turbo_button_value=$(do_get_ra_turbo_button_value "$ra_controller_input_cfg")
       [ "$tate_mode" = "true" ] && [ "$controller_name" == "$DEFAULT_CONTROLLER_NAME" ] && turbo_button_value=$(do_get_ra_turbo_button_tate_value "$ra_controller_input_cfg")
       #print_log $LOG_FILE "DEBUG" "Executing 'do_config_controllers_retroarch()' - controller '$player', index '$index', name '$controller_name', turbo button value '$turbo_button_value', TATE mode '$tate_mode'"
       if [ ! -z "$turbo_button_value" ]; then
          do_set_ra_turbo_button_value "$turbo_button_value" "$ra_controller_input_cfg"
       else
          do_remove_ra_turbo_button "$ra_controller_input_cfg"
       fi

       # configure hotkeys to player 1
       if [ "$player" -eq "1" ]; then
           #print_log $LOG_FILE "INFO" "Executing 'do_config_controllers_retroarch()' - controller '$player', index '$index', name '$controller_name', configuring hotkeys"
           do_config_hotkeys_retroarch "$config_file" "$ra_controller_input_cfg"
       fi
    done
}

do_config_controllers()
{
    local emulator=$1
    local config_file=$2
    local tate_mode=$3
    if [ -z "$tate_mode" ] || [ "$tate_mode" != "true" ]; then
       tate_mode="false"
    fi

    #print_log $LOG_FILE "INFO" "Executing 'do_config_controllers()' - emulator: '$emulator', configuration file: '$config_file', TATE mode '$tate_mode'"

    if [ -z "$emulator" ] || [ -z "$config_file" ] || [ ! -f "$config_file" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_config_controllers()' - emulator or configuration file are empty or not exist, skipping..."
        return
    fi

    emulator="${emulator^^}"

    case "${emulator}" in
        "RETROARCH")
            do_config_controllers_retroarch "$config_file" "$RA_AUTOCONFIG_FOLDER" "$tate_mode"
        ;;
        "RETROARCH32")
            do_config_controllers_retroarch "$config_file" "$RA32_AUTOCONFIG_FOLDER" "$tate_mode"
        ;;
    esac
}

do_remove_controllers_config_retroarch()
{
    local config_file=$1
    local autoconfig_folder=$2

    #print_log $LOG_FILE "INFO" "Executing 'do_remove_controllers_config_retroarch()' - configuration file: '$config_file'"

    local num_controllers=$(do_get_controllers_number)

    #print_log $LOG_FILE "INFO" "Executing 'do_remove_controllers_config_retroarch()' - configuration file: '$config_file', number of controllers: '$num_controllers'"

    for player in `seq 1 $num_controllers`
    do
       local position=$((player - 1))
       local index=$(cat "$INPUT_CONTROLLERS_CONFIG_PATH" | jq '.['"$position"'].index')

       # remove turbo button
       local controller_name=$(cat "$INPUT_CONTROLLERS_CONFIG_PATH" | jq '.['"$position"'].name')
       controller_name="${controller_name//\"/}"
       #print_log $LOG_FILE "INFO" "Executing 'do_remove_controllers_config_retroarch()' - controller '$player', index '$index', name '$controller_name'"
       [ "$controller_name" == "null" ] && continue

       local ra_controller_input_cfg="$autoconfig_folder/${controller_name}.cfg"
       do_remove_ra_turbo_button "$ra_controller_input_cfg"
    done

    #print_log $LOG_FILE "INFO" "Executing 'do_remove_controllers_config_retroarch()' - removing config files: '$config_file', '$INPUT_CONTROLLERS_CONFIG_PATH'"
    sudo rm -f "$INPUT_CONTROLLERS_CONFIG_PATH"
    sudo rm -f "$config_file"
}

do_remove_controllers_config()
{
    local emulator=$1
    local config_file=$2

    #print_log $LOG_FILE "INFO" "Executing 'do_remove_controllers_config()' - emulator: '$emulator', configuration file: '$config_file'"

    if [ -z "$emulator" ] || [ -z "$config_file" ] || [ ! -f "$config_file" ]; then
        #print_log $LOG_FILE "WARNING" "Executing 'do_remove_controllers_config()' - emulator or configuration file are empty or not exist, skipping..."
        return
    fi

    emulator="${emulator^^}"

    case "${emulator}" in
        "RETROARCH")
            do_remove_controllers_config_retroarch "$config_file" "$RA_AUTOCONFIG_FOLDER"
        ;;
        "RETROARCH32")
            do_remove_controllers_config_retroarch "$config_file" "$RA32_AUTOCONFIG_FOLDER"
        ;;
    esac
}

# ******************************************************************************************

# Configure ES commons variables
. es-log_scripts

LOG_FILE="$ES_SCRIPT_LOGS_DIR/es-controllers.log"
ES_INPUT_CFG_FILE="$ES_ETC_PATH/es_input.cfg"
DEFAULT_CONTROLLER_NAME="retrogame_joypad"
DEFAULT_RA_CONTROLLER_CONFIG_FILE="$RA_CONFIG_FOLDER/autoconfig/udev/$DEFAULT_CONTROLLER_NAME.cfg"
DEFAULT_RA_TURBO_BUTTON_PROPERTY="input_turbo_btn"
MAX_PLAYERS=5


#if [ -f "$LOG_FILE" ]; then
#  mv "$LOG_FILE" "$LOG_FILE.bak"
#fi

exit_execution()
{
    local return=$1
    local param1=$2
    local param2=$3
    local param3=$4
    #print_log $LOG_FILE "INFO" "##### Exit executing operation: '$ACTION $param1 $param2 $param3 $param4', result: '$return' #####"
    exit $return
}

if [ $# -eq 0 ]; then
  do_help
  exit 1
fi

ACTION=$1
shift

#print_log $LOG_FILE "INFO" "##### Executing operation: '${ACTION} $1 $2 $3' #####"

case "${ACTION}" in
    "set")
        do_config_set_value "$1" "$2" "$3" || exit_execution 1 "$1" "$2" "$3"
    ;;
    "get")
        do_config_get_value "$1" "$2"
    ;;
    "remove")
        do_config_remove_value "$1" "$2"
    ;;
    "config_controllers")
        do_config_controllers "$1" "$2" "$3" || exit_execution 1 "$1" "$2" "$3"
    ;;
    "remove_controllers_config")
        do_remove_controllers_config "$1" "$2" || exit_execution 1 "$1" "$2"
    ;;
    *)
        do_help
        >&2 echo "error: invalid command ${ACTION}"
        #print_log $LOG_FILE "ERROR" "##### Invalid command ${ACTION} #####"
        exit 1
esac

exit_execution 0 "$1" "$2" "$3"
