#!/bin/bash

if [ ! "$1" ];then
	printf "usage : es-cheevos set key value|get key]\n"
	printf "Valid keys: cheevos_enable, cheevos_hardcore_mode_enable, cheevos_leaderboards_enable, cheevos_verbose_enable, cheevos_auto_screenshot, cheevos_challenge_indicators, cheevos_richpresence_enable, cheevos_badges_enable, cheevos_test_unofficial, cheevos_start_active, cheevos_unlock_sound_enable, cheevos_unlock_sound, cheevos_sound_folders, cheevos_username, cheevos_password, cheevos_token\n"
	printf "or\n"
	printf "usage : es-cheevos set_all_values [cheevos_enable_value] [cheevos_hardcore_mode_value] [cheevos_leaderboards_value] [cheevos_verbose_value] [cheevos_auto_screenshot_value] [cheevos_challenge_value] [cheevos_richpresence_value] [cheevos_badges_value] [cheevos_test_unofficial_value] [cheevos_start_active_value] [sound_value] [username_value] [password_value]\n"
	exit 1
fi

# Configure ES commons variables
. es-commons

UNLOCK_SOUND_FOLDER="$RA_CONFIG_FOLDER/assets/sounds"
UNLOCK_SOUND_FILE="$UNLOCK_SOUND_FOLDER/unlock.ogg"
UNLOCK_SOUND_FILE_SAVE="$UNLOCK_SOUND_FILE.save"

restore_unlock_sound () {
	sleep 1
	set_ra_property $RA_CONFIG_FILE "cheevos_unlock_sound_enable" "false"
	set_ra_property $RA32_CONFIG_FILE "cheevos_unlock_sound_enable" "false"

	if [ -f "$UNLOCK_SOUND_FILE_SAVE" ]; then
		rm -f "$UNLOCK_SOUND_FILE"
		mv -f "$UNLOCK_SOUND_FILE_SAVE" "$UNLOCK_SOUND_FILE"
	fi

}

config_unlock_sound () {
		value_file=$1

		if [ "$value_file" = "none" ] || [ "$value_file" = "" ]; then
			restore_unlock_sound
			return 0
		else
			set_ra_property $RA_CONFIG_FILE "cheevos_unlock_sound_enable" "true"
			set_ra_property $RA32_CONFIG_FILE "cheevos_unlock_sound_enable" "true"

			if [ "$value_file" = "unlock" ]; then
				if [ -f "$UNLOCK_SOUND_FILE_SAVE" ]; then
					rm -f "$UNLOCK_SOUND_FILE"
					mv -f "$UNLOCK_SOUND_FILE_SAVE" "$UNLOCK_SOUND_FILE"
				fi
			else
				sound_file=$(find "$UNLOCK_SOUND_FOLDER" -type f -name "$value_file.ogg")
				if [ ! -f "$sound_file" ]; then
					sound_file=$(find "$HOME/sounds/retroachievements" -type f -name "$value_file.ogg")
				fi

				if [ -f "$sound_file" ]; then
					if [ ! -f "$UNLOCK_SOUND_FILE_SAVE" ]; then
						mv -f "$UNLOCK_SOUND_FILE" "$UNLOCK_SOUND_FILE_SAVE"
					fi
					cp -f "$sound_file" "$UNLOCK_SOUND_FILE"
				fi
			fi
		fi
}

get_unlock_sound_folders () {
	echo "$UNLOCK_SOUND_FOLDER\n$HOME/sounds/retroachievements"
}

config_set_value () {
	key=$1
	value=$2

	if [ "$key" = "cheevos_unlock_sound" ]; then
		config_unlock_sound $value
	else
		set_ra_property $RA_CONFIG_FILE $key $value
		set_ra_property $RA32_CONFIG_FILE $key $value
	fi
}

config_get_value () {
	key=$1

	if [ "$key" = "cheevos_sound_folders" ]; then
		get_unlock_sound_folders
	else
		get_ra_property "$RA_CONFIG_FILE" "$key"
	fi
}

config_set_all_values () {
	config_set_value "cheevos_enable" $1
	config_set_value "cheevos_hardcore_mode_enable" $2
	config_set_value "cheevos_leaderboards_enable" $3
	config_set_value "cheevos_verbose_enable" $4
	config_set_value "cheevos_auto_screenshot" $5
	config_set_value "cheevos_challenge_indicators" $6
	config_set_value "cheevos_richpresence_enable" $7
	config_set_value "cheevos_badges_enable" $8
	config_set_value "cheevos_test_unofficial" $9
	config_set_value "cheevos_start_active" $10
	config_set_value "cheevos_unlock_sound" $11
	config_set_value "cheevos_username" $12
	config_set_value "cheevos_password" $13
}


# ******************************************************************************************


command="$1"

if [ "$#" -eq 3 ]; then
	pkey="$2"
	pvalue="$3"
	if [ "$command" = "set" ]; then
		config_set_value $pkey $pvalue
		exit 0
	fi
elif [ "$#" -eq 2 ]; then
	pkey="$2"
	if [ "$command" = "get" ]; then
		config_get_value $pkey
	fi
elif [ "$#" -eq 14 ]; then
	if [ "$command" = "set_all_values" ]; then
		config_set_all_values "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "$10" "$11" "$12" "$13" "$14"
	fi
	exit 0
fi

