#!/bin/bash

aceptable_level()
{
  local log_level=$ES_DEFAULT_LOGGING_LEVEL

  case "$1" in
     "ERROR")
         log_level=$LOG_LEVEL_ERROR
       ;;
     "WARNING")
         log_level=$LOG_LEVEL_WARNING
        ;;
      "INFO")
          log_level=$LOG_LEVEL_INFO
        ;;
      "DEBUG")
          log_level=$LOG_LEVEL_DEBUG
        ;;
      *)
          log_level=$ES_DEFAULT_LOGGING_LEVEL
  esac

  if [ $log_level -gt $ES_LOGGING_LEVEL ]; then
    # not aceptable
    return 1
  fi
  # aceptable
  return 0
}

print_log()
{
  local log_file="$1"
  local log_level="$2"
  local log_mesage="$3"
  local mdate=""
  local PID=$$

  if [ $ES_LOGGING_ENABLED -eq 1 ]; then
    aceptable_level $log_level
    if [ $? -eq 0 ]; then
      if [ $ES_LOG_WITH_NANO -eq 1 ]; then
        mdate=$(date '+%d/%m/%Y %H:%M:%S:%N')
      else
        mdate=$(date '+%d/%m/%Y %H:%M:%S')
      fi
      local msg="$mdate [$PID] - $log_level $log_mesage"
      echo "$msg" >> $log_file
    fi
  fi
}

get_compatible_es_log_level()
{
  local log_level=$1

  if [ -z "$log_level" ]; then
    log_level=$ES_DEFAULT_LOGGING_LEVEL
  fi

  case "$1" in
     "error")
         log_level=$LOG_LEVEL_ERROR
       ;;
     "warning")
         log_level=$LOG_LEVEL_WARNING
        ;;
      "default")
          log_level=$LOG_LEVEL_INFO
        ;;
      "debug")
          log_level=$LOG_LEVEL_DEBUG
        ;;
      "disabled")
          log_level=$LOG_LEVEL_DISABLED
        ;;
      *)
          log_level=$ES_DEFAULT_LOGGING_LEVEL
        ;;
  esac

  echo "$log_level"
}

active_es_scripts_log_feature()
{
  local log_level=$1
  local log_with_nano=$2

  log_level="$(get_compatible_es_log_level $log_level)"

  sudo sed -i '/ES_LOGGING_ENABLED\=0/s//ES_LOGGING_ENABLED\=1/; /ES_LOGGING_LEVEL\=[[:digit:]]\+/s//ES_LOGGING_LEVEL\='"$log_level"'/; /ES_LOG_WITH_NANO\=[[:digit:]]\+/s//ES_LOG_WITH_NANO\='"$log_with_nano"'/' $ES_SCRIPTS_PATH/es-log_scripts
  grep -l print_log $ES_SCRIPTS_PATH/es-* | grep -v es-log_scripts | xargs sudo sed -i 's/#print_log/print_log/g'

  if [ -d "$ES_EVENTS_SCRIPTS_PATH" ]; then
    find "$ES_EVENTS_SCRIPTS_PATH" -type f -exec sudo sed -i 's/#print_log/print_log/g' {} \;
  fi
  if [ -d "$ES_USER_EVENTS_SCRIPTS_PATH" ]; then
    find "$ES_USER_EVENTS_SCRIPTS_PATH" -type f -exec sudo sed -i 's/#print_log/print_log/g' {} \;
  fi
}

inactive_es_scripts_log_feature()
{
  sudo sed -i '/ES_LOGGING_ENABLED\=1/s//ES_LOGGING_ENABLED\=0/; /ES_LOGGING_LEVEL\=[[:digit:]]\+/s//ES_LOGGING_LEVEL\='"$LOG_LEVEL_DISABLED"'/; /ES_LOG_WITH_NANO\=1/s//ES_LOG_WITH_NANO\=0/' $ES_SCRIPTS_PATH/es-log_scripts
  grep -l print_log $ES_SCRIPTS_PATH/es-* | grep -v es-log_scripts | xargs sudo sed -i 's/print_log/#print_log/g'

  if [ -d "$ES_EVENTS_SCRIPTS_PATH" ]; then
    find "$ES_EVENTS_SCRIPTS_PATH" -type f -exec sudo sed -i 's/print_log/#print_log/g' {} \;
  fi
  if [ -d "$ES_USER_EVENTS_SCRIPTS_PATH" ]; then
    find "$ES_USER_EVENTS_SCRIPTS_PATH" -type f -exec sudo sed -i 's/print_log/#print_log/g' {} \;
  fi
}

remove_es_scripts_log()
{
  sudo rm -f "$ES_SCRIPT_LOGS_DIR"/es-*.log*
}

do_active_es_scripts_log() {
  local log_status=$1
  local log_level=$2
  local log_with_nano=$3

  if [ "$log_with_nano" = "true" ]; then
    log_with_nano=1
  else
    log_with_nano=0
  fi

  if [ "$log_status" = "true" ]; then
    active_es_scripts_log_feature "$log_level" "$log_with_nano"
  else
    inactive_es_scripts_log_feature
  fi
}

set_es_scripts_log_level()
{
  local log_level=$1

  log_level="$(get_compatible_es_log_level $log_level)"
  sudo sed -i '/ES_LOGGING_LEVEL\=[[:digit:]]\+/s//ES_LOGGING_LEVEL\='"$log_level"'/' $ES_SCRIPTS_PATH/es-log_scripts
}

is_actived_scripts_log() {
  if [ $ES_LOGGING_ENABLED -eq 0 ]; then
    echo "false"
  else
    echo "true"
  fi
}

do_enable_log_with_nano()
{
  sudo sed -i '/ES_LOG_WITH_NANO\=0/s//ES_LOG_WITH_NANO\=1/' $ES_SCRIPTS_PATH/es-log_scripts
}

do_disable_log_with_nano()
{
  sudo sed -i '/ES_LOG_WITH_NANO\=1/s//ES_LOG_WITH_NANO\=0/' $ES_SCRIPTS_PATH/es-log_scripts
}


# ******************************************************************************************

# Configure ES commons variables
. es-commons


#export ES_SCRIPT_LOGS_DIR="$ES_HOME_PATH"
export ES_SCRIPT_LOGS_DIR="$ROMS_DIR/logs"
if [ ! -d "$ES_SCRIPT_LOGS_DIR" ]; then
  sudo mkdir "$ES_SCRIPT_LOGS_DIR"
fi

# LOG Levels:
LOG_LEVEL_ERROR=0
LOG_LEVEL_WARNING=1
LOG_LEVEL_INFO=2
LOG_LEVEL_DEBUG=3
LOG_LEVEL_DISABLED=4

ES_LOGGING_ENABLED=0
ES_DEFAULT_LOGGING_LEVEL=$LOG_LEVEL_INFO
ES_LOGGING_LEVEL=4
ES_LOG_WITH_NANO=0


case "${1}" in
    "active_es_scripts_log")
        do_active_es_scripts_log "$2" "$3" "$4"
        remove_es_scripts_log
    ;;
    "set_es_scripts_log_level")
        set_es_scripts_log_level "$2"
    ;;
    "is_actived_scripts_log")
        is_actived_scripts_log
    ;;
    "enable_log_with_nano")
        do_enable_log_with_nano
    ;;
    "disable_log_with_nano")
        do_disable_log_with_nano
    ;;
esac
