#!/bin/bash

if [ ! "$1" ];then
	printf "usage : es-overclock_system set [true/false] | get\n"
	exit 1
fi

#****************** boot *************************
bootConfigFile="/boot/extlinux/extlinux.conf"
NORMAL_DTB="rk3566.dtb"
OC_DTB="rk3566-OC.dtb"

overclock_on() {
  sudo sed -i "s#$NORMAL_DTB#$OC_DTB#g" "$bootConfigFile"
}

overclock_off() {
  sudo sed -i "s#$OC_DTB#$NORMAL_DTB#g" "$bootConfigFile"
}

overclock_system () {
  cat "$bootConfigFile" | grep -iw "$OC_DTB" > /dev/null
  valPresent=$?

  if [ "$valPresent" != "0" ]; then
    overclock_on
  else
    exit -1
  fi

}

normal_system () {
  cat "$bootConfigFile" | grep -iw "$OC_DTB" > /dev/null
  valPresent=$?

  if [ "$valPresent" != "0" ]; then
    # ignore
    exit -1
  else
    overclock_off
  fi
}


config_set_value () {
  value="$1"

  if [ "$value" = "true" ]; then
    overclock_system
  else
    normal_system
  fi
}


config_get_value () {
  cat "$bootConfigFile" | grep -iw "$OC_DTB" > /dev/null
  valPresent=$?

  if [ "$valPresent" != "0" ]; then
    echo "false"
  else
    echo "true"
  fi
}


# ******************************************************************************************

command="$1"

if [ "$#" -eq 2 ]; then
	pvalue="$2"
	if [ "$command" = "set" ]; then
		config_set_value $pvalue
		exit 0
	fi
elif [ "$#" -eq 1 ]; then
	if [ "$command" = "get" ]; then
		config_get_value
	fi
fi
