#!/bin/bash

if [ ! "$1" ];then
	printf "usage : es-overclock_system set [true/false] | get\n"
	exit 1
fi

#****************** boot *************************
BOOT_PART="/boot"
bootConfigFile="/$BOOT_PART/boot.ini"


overclock_on() {
  NORMAL_DTB="$1"
  OC_DTB="$2"
  device_folder="$3"

  #flash rw
  sudo sed -i "s#$NORMAL_DTB#${OC_DTB}#g" "$bootConfigFile"

  cat "$bootConfigFile" | grep -iw "max_cpufreq" > /dev/null
  valPresent=$?

  if [ "$valPresent" != "0" ]; then
    sudo sed -i -e "s/#\?consoleblank=0/consoleblank=0 max_cpufreq=1368/g" "$bootConfigFile" > /dev/null
  else
    sudo sed -i -e "s/#\?max_cpufreq=[0-9]\+/max_cpufreq=1368/g" "$bootConfigFile" > /dev/null
  fi

  sudo cp -f "$device_folder/$NORMAL_DTB" "$BOOT_PART"
  sudo cp -f "$device_folder/$OC_DTB" "$BOOT_PART"
  #flash ro
}

overclock_off() {
  NORMAL_DTB="$1"
  OC_DTB="$2"
  device_folder="$3"

  #flash rw
  sudo sed -i "s#$OC_DTB#$NORMAL_DTB#g" "$bootConfigFile"

  cat "$bootConfigFile" | grep -iw "max_cpufreq" > /dev/null
  valPresent=$?

  if [ "$valPresent" != "0" ]; then
    sudo sed -i -e "s/#\?consoleblank=0/consoleblank=0 max_cpufreq=1296/g" "$bootConfigFile" > /dev/null
  else
    sudo sed -i -e "s/#\?max_cpufreq=[0-9]\+/max_cpufreq=1296/g" "$bootConfigFile" > /dev/null
  fi

  sudo cp -f "$device_folder/$NORMAL_DTB" "$BOOT_PART"
  sudo cp -f "$device_folder/$OC_DTB" "$BOOT_PART"
  #flash ro
}

overclock_system () {
  device="ogs"
  device_base_folder="/opt/.retrooz"
  dtb_file="rk3326-odroidgo3-linux.dtb"
  dtb_oc_file="rk3326-odroidgo3-linux-oc.dtb"


  if [ -f "/opt/.retrooz/device" ]; then
    device=$(cat "/opt/.retrooz/device")
  fi
  if [ "$device" = "oga" ] || [ "$device" = "oga1" ]; then
    dtb_file="rk3326-odroidgo2-linux.dtb"
    dtb_oc_file="rk3326-odroidgo2-linux-oc.dtb"
  fi

  if [ ! -f "$device_base_folder/$device/$dtb_oc_file" ]; then
    exit -1
  fi

  cat "$bootConfigFile" | grep -iw "$dtb_oc_file" > /dev/null
  valPresent=$?

  if [ "$valPresent" != "0" ]; then
    overclock_on "$dtb_file" "$dtb_oc_file" "/$device_base_folder/$device"
  else
    exit -1
  fi

}

normal_system () {
  device="ogs"
  device_base_folder="/opt/.retrooz"
  dtb_file="rk3326-odroidgo3-linux.dtb"
  dtb_oc_file="rk3326-odroidgo3-linux-oc.dtb"

  if [ -f "/opt/.retrooz/device" ]; then
    device=$(cat "/opt/.retrooz/device")
  fi
  if [ "$device" = "oga" ] || [ "$device" = "oga1" ]; then
    dtb_file="rk3326-odroidgo2-linux.dtb"
    dtb_oc_file="rk3326-odroidgo2-linux-oc.dtb"
  fi

  if [ ! -f "/$device_base_folder/$device/$dtb_oc_file" ]; then
    exit -1
  fi

  cat "$bootConfigFile" | grep -iw "$dtb_oc_file" > /dev/null
  valPresent=$?

  if [ "$valPresent" != "0" ]; then
    # ignore
    exit -1
  else
    overclock_off "$dtb_file" "$dtb_oc_file" "/$device_base_folder/$device"
  fi
}


config_set_value () {
  value="$1"

  if [ "$value" = "true" ]; then
    overclock_system
  else
    normal_system
  fi
}


config_get_value () {
  cat "$bootConfigFile" | grep -iw "linux-oc.dtb" > /dev/null
  valPresent=$?

  if [ "$valPresent" != "0" ]; then
    echo "false"
  else
    echo "true"
  fi
}


# ******************************************************************************************

command="$1"

if [ "$#" -eq 2 ]; then
	pvalue="$2"
	if [ "$command" = "set" ]; then
		config_set_value $pvalue
		exit 0
	fi
elif [ "$#" -eq 1 ]; then
	if [ "$command" = "get" ]; then
		config_get_value
	fi
fi
