#!/bin/sh

if [ ! "$1" ];then
	printf "usage : es-show_fps set key value|get key]\n"
	printf "Valid keys: fps_show\n"
	exit 1
fi

# Configure ES commons variables
. es-commons

raConfigFolder="$RA_CONFIG_FOLDER"
raConfigFile="$raConfigFolder/retroarch.cfg"
ra32ConfigFolder="$RA32_CONFIG_FOLDER"
ra32ConfigFile="$ra32ConfigFolder/retroarch.cfg"

set_ra_value () {
	configFile=$1
	key=$2
	value=$3

	[ -z "$value" ] && value=0
	cat "$configFile" | grep -iw "$key" > /dev/null
	valPresent=$?

	if [ "$valPresent" != "0" ]; then
		echo "$key = \"$value\"" | sudo tee -a "$configFile" > /dev/null
	else
		sudo sed -i "s/#\?$key =.*/$key = \"$value\"/g" "$configFile" > /dev/null
	fi
}

config_set_ra_value () {
	key=$1
	value=$2

	set_ra_value $raConfigFile $key $value
	set_ra_value $ra32ConfigFile $key $value
}

config_get_ra_value () {
	key=$1

	sed -rn "s/^$key = \"([^\n]+)\"$/\1/p" "$raConfigFile"
}

config_set_value () {
	config_set_ra_value $1 $2
}

config_get_value () {
	config_get_ra_value $1
}


# ******************************************************************************************


command="$1"

if [ "$#" -eq 3 ]; then
	pkey="$2"
	pvalue="$3"
	if [ "$command" = "set" ]; then
		config_set_value $pkey $pvalue
		exit 0
	fi
elif [ "$#" -eq 2 ]; then
	pkey="$2"
	if [ "$command" = "get" ]; then
		config_get_value $pkey
	fi
fi
